### ISSUE TITLE
Create a PYTHON Live Connection PBIX Field Renamer

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#533]

**Comment by jesusitd** [comment]
Python created, backed up here:
https://gist.github.com/jesusitd/a1bab5471cf2722daa0bdc26e621df0e

**Comment by jesusitd** [comment]
Launching task:
- For the sets of files specified below (Operations workspace, TV 2.0 dataset):
```
\- Reports Live\Operations\Bogus Leads.pbix"
\- Reports Live\Operations\Campaign Routing.pbix"
\- Reports Live\Operations\Data Sweep - Operations.pbix"
\- Reports Live\Operations\Duplicate Leads and Cases.pbix"
\- Reports Live\Operations\Intake - Lead Vision Ads - All Case Types.pbix"
\- Reports Live\Operations\Intake Agent Performance 2.0.pbix"
\- Reports Live\Operations\Payroll Report.pbix"
\- Reports Live\Operations\Performance Monitors.pbix"
\- Reports Live\Operations\Pipeline Reports.pbix"
```

**Comment by jesusitd** [comment]
Rename operation complete.

**Comment by jesusitd** [comment]
List of renamed fileds:
```yaml
- old: lead_form_round_up_cancer_diagnosed
  new: Lead Form Roundup Cancer Diagnosed
- old: lead_form_round_up_cancer_diagnosis_age
  new: Lead Form Roundup Cancer Diagnosis Age
- old: lead_form_round_up_cancer_diagnosis_date
  new: Lead Form Roundup Cancer Diagnosis Date
- old: lead_form_round_up_location
  new: Lead Form Roundup Location
- old: lead_form_round_up_other_attorney
  new: Lead Form Roundup Other Attorney
- old: lead_form_round_up_usage_length
  new: Lead Form Roundup Usage Length
- old: lead_form_round_up_used
  new: Lead Form Roundup Used
- old: lead_form_talcum_powder_cancer_diagnosed
  new: Lead Form Talcum Powder Cancer Diagnosed
- old: lead_form_talcum_powder_cancer_diagnosis_date
  new: Lead Form Talcum Powder Cancer Diagnosis Date
- old: lead_form_talcum_powder_cancer_type
  new: Lead Form Talcum Powder Cancer Type
- old: lead_form_talcum_powder_other_attorney
  new: Lead Form Talcum Powder Other Attorney
- old: lead_form_talcum_powder_usage_length
  new: Lead Form Talcum Powder Usage Length
- old: lead_form_talcum_powder_used
  new: Lead Form Talcum Powder Used
- old: lead_form_hernia_mesh_complications_experienced
  new: Lead Form Hernia Mesh Complications Experienced
- old: lead_form_hernia_mesh_implant_year_range
  new: Lead Form Hernia Mesh Implant Year Range
- old: lead_form_hernia_mesh_other_attorney
  new: Lead Form Hernia Mesh Other Attorney
- old: lead_form_hernia_mesh_revision_surgery_year_range
  new: Lead Form Hernia Mesh Revision Surgery Year Range
- old: lead_form_hernia_mesh_revision_surgery
  new: Lead Form Hernia Mesh Revision Surgery
- old: lead_form_taxotere_treatment_date
  new: Lead Form Taxotere Treatment Date
- old: lead_form_taxotere_injury_hair_loss
  new: Lead Form Taxotere Injury Hair Loss
- old: lead_form_taxotere_other_attorney
  new: Lead Form Taxotere Other Attorney
- old: lead_form_ivc_other_attorney
  new: Lead Form IVC Other Attorney
- old: lead_form_ivc_injuries
  new: Lead Form IVC Injuries
- old: lead_form_ivc_filter_brand
  new: Lead Form IVC Filter Brand
- old: lead_form_ivc_filter_implanted
  new: Lead Form IVC Filter Implanted
- old: lead_form_ivc_implant_type
  new: Lead Form IVC Implant Type
```
